{"uid":"21b3abb8e47f4d49","name":"test_join_community_with_low_bandwith","fullName":"tests.test_join_community.TestJoinCommunity#test_join_community_with_low_bandwith","historyId":"acec66a9fe6a2fbcbf702c9ea545d881","time":{"start":1724633261470,"stop":1724633416098,"duration":154628},"status":"broken","statusMessage":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=23313): Read timed out. (read timeout=10)","statusTrace":"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=23313): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_join_community.py:66: in test_join_community_with_low_bandwith\n    self.test_join_community_baseline()\ntests/test_join_community.py:20: in test_join_community_baseline\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:170: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:22: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=23313): Read timed out. (read timeout=10)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1724631053125,"stop":1724631053125,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1724633253660,"stop":1724633253660,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1724633253660,"stop":1724633253660,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1724633253660,"stop":1724633261470,"duration":7810},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=23313): Read timed out. (read timeout=10)","statusTrace":"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=23313): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_join_community.py:66: in test_join_community_with_low_bandwith\n    self.test_join_community_baseline()\ntests/test_join_community.py:20: in test_join_community_baseline\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:170: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:22: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=23313): Read timed out. (read timeout=10)","steps":[],"attachments":[{"uid":"c8996be3054d5740","name":"log","source":"c8996be3054d5740.txt","type":"text/plain","size":333784}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1724633416302,"stop":1724633416304,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1724633416304,"stop":1724633416497,"duration":193},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1724634553108,"stop":1724634553108,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_join_community"},{"name":"subSuite","value":"TestJoinCommunity"},{"name":"host","value":"fv-az885-63"},{"name":"thread","value":"10228-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_join_community"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":23,"broken":6,"skipped":0,"passed":18,"unknown":0,"total":47},"items":[{"uid":"ac801d027abed454","reportUrl":"https://status-im.github.io/status-cli-tests/179//#testresult/ac801d027abed454","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=42820): Read timed out. (read timeout=10)","time":{"start":1724546756339,"stop":1724546837588,"duration":81249}},{"uid":"89b41d5a083fee8c","reportUrl":"https://status-im.github.io/status-cli-tests/178//#testresult/89b41d5a083fee8c","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=20964): Read timed out. (read timeout=10)","time":{"start":1724460339723,"stop":1724460479156,"duration":139433}},{"uid":"ae20ae6933a41b03","reportUrl":"https://status-im.github.io/status-cli-tests/177//#testresult/ae20ae6933a41b03","status":"passed","time":{"start":1724373654298,"stop":1724373733653,"duration":79355}},{"uid":"1e5c9b198a62a66e","reportUrl":"https://status-im.github.io/status-cli-tests/176//#testresult/1e5c9b198a62a66e","status":"passed","time":{"start":1724287198939,"stop":1724287236593,"duration":37654}},{"uid":"6f99dfe05f619fae","reportUrl":"https://status-im.github.io/status-cli-tests/175//#testresult/6f99dfe05f619fae","status":"passed","time":{"start":1724257236662,"stop":1724257274351,"duration":37689}},{"uid":"daac14c9c5c66970","reportUrl":"https://status-im.github.io/status-cli-tests/174//#testresult/daac14c9c5c66970","status":"passed","time":{"start":1724242492074,"stop":1724242529675,"duration":37601}},{"uid":"8f617086b52f26a7","reportUrl":"https://status-im.github.io/status-cli-tests/173//#testresult/8f617086b52f26a7","status":"failed","statusDetails":"AssertionError: 3 community joins out of 10: Join Timestamp: 10:43:16, Accept Timestamp: 10:43:24,Community ID: 0x03b35a6ea06115c3d362f232062545e530d7d41dc80392bb7bf5e87b3eb1be0f68, Error: Comunity doesn't have correct number of members so second node didn't managed to join\nassert 2 >= (8 + 1)\n +  where 2 = len({'0x0471a0e8548904b879a4909bbf0af029b50945fd34bab87736289ad39b03a1cefb5bcfba7545a6bce158b6b2ebd682c8a99cde5f4b15c526fb976f5f86fa2ed363': {'last_update_clock': 1724236997}, '0x0480a14c753794f9b23b6ba54c56ce04b3c0cf66201a7b8eb7a5641a642a2c361c2dc3211af7352ba27a0d4e5cb4be6416cc59105ad49f7f390f08d40dd679709d': {'roles': [1]}})\nJoin Timestamp: 10:43:17, Accept Timestamp: 10:43:25,Community ID: 0x0310b2d4bff2292cbc9f229008bdaf77cfc939ade6da9912efcd45e1150ba3fab4, Error: Comunity doesn't have correct number of members so second node didn't managed to join\nassert 2 >= (11 + 1)\n +  where 2 = len({'0x0471a0e8548904b879a4909bbf0af029b50945fd34bab87736289ad39b03a1cefb5bcfba7545a6bce158b6b2ebd682c8a99cde5f4b15c526fb976f5f86fa2ed363': {'last_update_clock': 1724236997}, '0x0478c40b4782c10ec60095d5a8fb7457c0fc98924dc14dc77442b2f9f9d65cc02361837b322a4639fdbdcbf5cb82776a99a730be8f3ad836a4e78ac57c6cc8b9b5': {'roles': [1]}})\nJoin Timestamp: 10:43:17, Accept Timestamp: 10:43:27,Community ID: 0x021e2785163d8e3c323915d127cd60e16035b9ec7399395711e0919900948455e5, Error: Comunity doesn't have correct number of members so second node didn't managed to join\nassert 2 >= (10 + 1)\n +  where 2 = len({'0x0471a0e8548904b879a4909bbf0af029b50945fd34bab87736289ad39b03a1cefb5bcfba7545a6bce158b6b2ebd682c8a99cde5f4b15c526fb976f5f86fa2ed363': {'last_update_clock': 1724236997}, '0x04797c0ca5573f1b9ab73246fa9f655a53617bc41b23ba12bc0348effa6fd604ee59aef3dc8c09f850a56c231affaa56bf03abd489254a9ce0f792178840ea28bf': {'roles': [1]}})","time":{"start":1724236970373,"stop":1724237008985,"duration":38612}},{"uid":"b361555bbdcfe7f5","reportUrl":"https://status-im.github.io/status-cli-tests/172//#testresult/b361555bbdcfe7f5","status":"failed","statusDetails":"AssertionError: 1 community joins out of 10: Join Timestamp: 00:40:45, Accept Timestamp: 00:40:51,Community ID: 0x03b35a6ea06115c3d362f232062545e530d7d41dc80392bb7bf5e87b3eb1be0f68, Error: Comunity doesn't have correct number of members so second node didn't managed to join\nassert 16 == (1 + 1)\n +  where 16 = len({'0x040e2759e05ceee3542780ab42f4008052b149990320813c1f7175d95ae1aee12b01b7df67245fb345fcd711648558d9c54011fb0afea619fc4a9cb5ee15b29c8b': {'last_update_clock': 1724161842}, '0x041fcbc4449ced2f4205597d1fb0f4506b44e0659f98cc56ea4e3b5b1d4cb026401c3ea5f7695f2f18fa5b9f76e150a11ec1429f02c59f2959da04244dfc7cd317': {'last_update_clock': 1724161657}, '0x042ba411422281182b3e52c2314e9895c1a0920b2119074e3e1ce57ff4ad15835855d6f4de777e10bd7b4cfe33497e2e1d9f951164330cc82c65561ad8fa44ff64': {'last_update_clock': 1724200846}, '0x042d180a162e6ecac0ce9ea7e0c2814777312cfe77b6ea588166b1a038fa5cc6382a31879f1e5ae8c789029d984be5c97ac7124a7ffe8a585cd636921e36f969b4': {'last_update_clock': 1724161979}, ...})","time":{"start":1724200818905,"stop":1724200856557,"duration":37652}},{"uid":"70c91de46605625e","reportUrl":"https://status-im.github.io/status-cli-tests/171//#testresult/70c91de46605625e","status":"passed","time":{"start":1724161816456,"stop":1724161854115,"duration":37659}},{"uid":"9e359cf0c3c04c93","reportUrl":"https://status-im.github.io/status-cli-tests/170//#testresult/9e359cf0c3c04c93","status":"failed","statusDetails":"AssertionError","time":{"start":1724157399564,"stop":1724157434200,"duration":34636}},{"uid":"d86cbd1617d93594","reportUrl":"https://status-im.github.io/status-cli-tests/168//#testresult/d86cbd1617d93594","status":"failed","statusDetails":"AssertionError","time":{"start":1724114113509,"stop":1724114148117,"duration":34608}},{"uid":"5ba6ecf34bba73f2","reportUrl":"https://status-im.github.io/status-cli-tests/167//#testresult/5ba6ecf34bba73f2","status":"failed","statusDetails":"AssertionError","time":{"start":1724027729885,"stop":1724027764481,"duration":34596}},{"uid":"af9d25ec9817287d","reportUrl":"https://status-im.github.io/status-cli-tests/166//#testresult/af9d25ec9817287d","status":"failed","statusDetails":"AssertionError","time":{"start":1723941406741,"stop":1723941442426,"duration":35685}},{"uid":"597db28e7c465fc0","reportUrl":"https://status-im.github.io/status-cli-tests/165//#testresult/597db28e7c465fc0","status":"failed","statusDetails":"AssertionError","time":{"start":1723854924508,"stop":1723854959115,"duration":34607}},{"uid":"1769ad009a2dd258","reportUrl":"https://status-im.github.io/status-cli-tests/164//#testresult/1769ad009a2dd258","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=42152): Read timed out. (read timeout=2)","time":{"start":1723768564133,"stop":1723768609361,"duration":45228}},{"uid":"e5b2aa4a931c171e","reportUrl":"https://status-im.github.io/status-cli-tests/163//#testresult/e5b2aa4a931c171e","status":"failed","statusDetails":"AssertionError","time":{"start":1723682120321,"stop":1723682154915,"duration":34594}},{"uid":"eb8a474a07ff25d2","reportUrl":"https://status-im.github.io/status-cli-tests/162//#testresult/eb8a474a07ff25d2","status":"failed","statusDetails":"AssertionError","time":{"start":1723595696829,"stop":1723595731482,"duration":34653}},{"uid":"6a899905cb6eeb8f","reportUrl":"https://status-im.github.io/status-cli-tests/161//#testresult/6a899905cb6eeb8f","status":"failed","statusDetails":"AssertionError","time":{"start":1723509356989,"stop":1723509391907,"duration":34918}},{"uid":"aac2a83daa620659","reportUrl":"https://status-im.github.io/status-cli-tests/160//#testresult/aac2a83daa620659","status":"failed","statusDetails":"AssertionError","time":{"start":1723422859682,"stop":1723422894266,"duration":34584}},{"uid":"380340fcf5589029","reportUrl":"https://status-im.github.io/status-cli-tests/159//#testresult/380340fcf5589029","status":"failed","statusDetails":"AssertionError","time":{"start":1723336668798,"stop":1723336706917,"duration":38119}}]},"tags":["@pytest.mark.usefixtures('start_1_node')"]},"source":"21b3abb8e47f4d49.json","parameterValues":[]}