{"uid":"f3ecdad4cf551d4e","name":"test_fetch_community_with_latency","fullName":"tests.test_fetch_community.TestFetchCommunity#test_fetch_community_with_latency","historyId":"b219078e02c2b2383da3ebd6787c88d5","time":{"start":1736209986798,"stop":1736210045935,"duration":59137},"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:57712 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=57712): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=57712): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_fetch_community.py:33: in test_fetch_community_with_latency\n    self.test_fetch_community_baseline()\ntests/test_fetch_community.py:18: in test_fetch_community_baseline\n    response = self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:57712 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1736209022166,"stop":1736209022166,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1736209978986,"stop":1736209978987,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1736209978986,"stop":1736209978986,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1736209978987,"stop":1736209986797,"duration":7810},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:57712 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=57712): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=57712): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_fetch_community.py:33: in test_fetch_community_with_latency\n    self.test_fetch_community_baseline()\ntests/test_fetch_community.py:18: in test_fetch_community_baseline\n    response = self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:57712 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","steps":[],"attachments":[{"uid":"cc6bd478daa70b36","name":"log","source":"cc6bd478daa70b36.txt","type":"text/plain","size":99961}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1736210046112,"stop":1736210046114,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1736210046115,"stop":1736210046235,"duration":120},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1736211039776,"stop":1736211039776,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_fetch_community"},{"name":"subSuite","value":"TestFetchCommunity"},{"name":"host","value":"fv-az1910-173"},{"name":"thread","value":"60592-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_fetch_community"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":53,"skipped":0,"passed":37,"unknown":0,"total":90},"items":[{"uid":"f8f994a34cbf355","reportUrl":"https://status-im.github.io/status-cli-tests/327//#testresult/f8f994a34cbf355","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:14328 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1736123529018,"stop":1736123586100,"duration":57082}},{"uid":"759559263bfe48","reportUrl":"https://status-im.github.io/status-cli-tests/326//#testresult/759559263bfe48","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:44947 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1736037203924,"stop":1736037261070,"duration":57146}},{"uid":"ac4d5334fae9bf50","reportUrl":"https://status-im.github.io/status-cli-tests/325//#testresult/ac4d5334fae9bf50","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:20075 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735950692072,"stop":1735950748832,"duration":56760}},{"uid":"2c1150c7e2b49ba0","reportUrl":"https://status-im.github.io/status-cli-tests/324//#testresult/2c1150c7e2b49ba0","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:40725 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735864240718,"stop":1735864297710,"duration":56992}},{"uid":"b6700e722b08ccec","reportUrl":"https://status-im.github.io/status-cli-tests/323//#testresult/b6700e722b08ccec","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:40910 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735777812979,"stop":1735777870023,"duration":57044}},{"uid":"6b2fb683e4d047ed","reportUrl":"https://status-im.github.io/status-cli-tests/322//#testresult/6b2fb683e4d047ed","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:20742 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735691529381,"stop":1735691586459,"duration":57078}},{"uid":"d39acb2db6f5c6e2","reportUrl":"https://status-im.github.io/status-cli-tests/321//#testresult/d39acb2db6f5c6e2","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:14884 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735605026878,"stop":1735605083659,"duration":56781}},{"uid":"3df57985e6a97c6b","reportUrl":"https://status-im.github.io/status-cli-tests/320//#testresult/3df57985e6a97c6b","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:19108 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735518661259,"stop":1735518719333,"duration":58074}},{"uid":"741719fe07aca925","reportUrl":"https://status-im.github.io/status-cli-tests/319//#testresult/741719fe07aca925","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:51815 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735432307975,"stop":1735432365070,"duration":57095}},{"uid":"ea910735674e963b","reportUrl":"https://status-im.github.io/status-cli-tests/318//#testresult/ea910735674e963b","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:49908 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735345867686,"stop":1735345924575,"duration":56889}},{"uid":"d2d5f00eae1e36d1","reportUrl":"https://status-im.github.io/status-cli-tests/317//#testresult/d2d5f00eae1e36d1","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:8090 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735259528764,"stop":1735259603419,"duration":74655}},{"uid":"bff78115d028ed32","reportUrl":"https://status-im.github.io/status-cli-tests/316//#testresult/bff78115d028ed32","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:39398 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735172998050,"stop":1735173072725,"duration":74675}},{"uid":"3e14d647a6f796ea","reportUrl":"https://status-im.github.io/status-cli-tests/315//#testresult/3e14d647a6f796ea","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:42485 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735086604951,"stop":1735086679621,"duration":74670}},{"uid":"ad618e7f0933ed30","reportUrl":"https://status-im.github.io/status-cli-tests/314//#testresult/ad618e7f0933ed30","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:36909 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735000200461,"stop":1735000264087,"duration":63626}},{"uid":"41ab3a7f5ed97c2e","reportUrl":"https://status-im.github.io/status-cli-tests/313//#testresult/41ab3a7f5ed97c2e","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:29220 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1734913861288,"stop":1734913922213,"duration":60925}},{"uid":"a176dd129d9cd680","reportUrl":"https://status-im.github.io/status-cli-tests/312//#testresult/a176dd129d9cd680","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:10880 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1734827495477,"stop":1734827555185,"duration":59708}},{"uid":"20e0c459a153b6b5","reportUrl":"https://status-im.github.io/status-cli-tests/311//#testresult/20e0c459a153b6b5","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:53691 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1734741013434,"stop":1734741071797,"duration":58363}},{"uid":"bdf901b977a4c3f5","reportUrl":"https://status-im.github.io/status-cli-tests/310//#testresult/bdf901b977a4c3f5","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:45245 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1734654604576,"stop":1734654661397,"duration":56821}},{"uid":"a80523ecbd28a730","reportUrl":"https://status-im.github.io/status-cli-tests/309//#testresult/a80523ecbd28a730","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:14633 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1734568177126,"stop":1734568234933,"duration":57807}},{"uid":"3182e3a60eef0ba1","reportUrl":"https://status-im.github.io/status-cli-tests/308//#testresult/3182e3a60eef0ba1","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:48157 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1734481929126,"stop":1734482074342,"duration":145216}}]},"tags":["@pytest.mark.usefixtures('start_1_node')"]},"source":"f3ecdad4cf551d4e.json","parameterValues":[]}