{"uid":"d914f5d744184bf","name":"test_leave_community_with_low_bandwith","fullName":"tests.test_leave_community.TestLeaveCommunity#test_leave_community_with_low_bandwith","historyId":"002f4e0ce6059e6f50dfb45299dc7da2","time":{"start":1726015480667,"stop":1726015535172,"duration":54505},"status":"broken","statusMessage":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=5807): Read timed out. (read timeout=10)","statusTrace":"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=5807): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_leave_community.py:52: in test_leave_community_with_low_bandwith\n    self.join_created_communities()\nsrc/steps/common.py:174: in join_created_communities\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:170: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:22: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=5807): Read timed out. (read timeout=10)","flaky":true,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1726013462488,"stop":1726013462488,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1726015472854,"stop":1726015480666,"duration":7812},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1726015472854,"stop":1726015472854,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1726015472854,"stop":1726015472854,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=5807): Read timed out. (read timeout=10)","statusTrace":"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=5807): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_leave_community.py:52: in test_leave_community_with_low_bandwith\n    self.join_created_communities()\nsrc/steps/common.py:174: in join_created_communities\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:170: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:22: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=5807): Read timed out. (read timeout=10)","steps":[],"attachments":[{"uid":"daf97324e0edc79","name":"log","source":"daf97324e0edc79.txt","type":"text/plain","size":49586}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1726015535397,"stop":1726015535399,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1726015535399,"stop":1726015535595,"duration":196},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1726016266416,"stop":1726016266416,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_leave_community"},{"name":"subSuite","value":"TestLeaveCommunity"},{"name":"host","value":"fv-az1144-627"},{"name":"thread","value":"10244-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_leave_community"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":33,"broken":11,"skipped":0,"passed":19,"unknown":0,"total":63},"items":[{"uid":"8e0d825f4578531c","reportUrl":"https://status-im.github.io/status-cli-tests/195//#testresult/8e0d825f4578531c","status":"passed","time":{"start":1725929222728,"stop":1725929270976,"duration":48248}},{"uid":"a8fa4f86c6955c","reportUrl":"https://status-im.github.io/status-cli-tests/194//#testresult/a8fa4f86c6955c","status":"passed","time":{"start":1725842604506,"stop":1725842667578,"duration":63072}},{"uid":"b49c4fe9d4031244","reportUrl":"https://status-im.github.io/status-cli-tests/193//#testresult/b49c4fe9d4031244","status":"failed","statusDetails":"AssertionError","time":{"start":1725756467666,"stop":1725756531442,"duration":63776}},{"uid":"68bfe7347eff4ebf","reportUrl":"https://status-im.github.io/status-cli-tests/192//#testresult/68bfe7347eff4ebf","status":"failed","statusDetails":"AssertionError","time":{"start":1725669962643,"stop":1725670044385,"duration":81742}},{"uid":"8f3e0da6d963067d","reportUrl":"https://status-im.github.io/status-cli-tests/191//#testresult/8f3e0da6d963067d","status":"failed","statusDetails":"AssertionError","time":{"start":1725583556305,"stop":1725583613440,"duration":57135}},{"uid":"aab736f1524cd4a0","reportUrl":"https://status-im.github.io/status-cli-tests/190//#testresult/aab736f1524cd4a0","status":"failed","statusDetails":"AssertionError","time":{"start":1725497254029,"stop":1725497348768,"duration":94739}},{"uid":"50ef440925197eaa","reportUrl":"https://status-im.github.io/status-cli-tests/189//#testresult/50ef440925197eaa","status":"failed","statusDetails":"AssertionError","time":{"start":1725410581372,"stop":1725410638099,"duration":56727}},{"uid":"4b564c05b3980630","reportUrl":"https://status-im.github.io/status-cli-tests/188//#testresult/4b564c05b3980630","status":"failed","statusDetails":"AssertionError","time":{"start":1725324330533,"stop":1725324390295,"duration":59762}},{"uid":"e837b07cdf5c0b56","reportUrl":"https://status-im.github.io/status-cli-tests/187//#testresult/e837b07cdf5c0b56","status":"failed","statusDetails":"AssertionError","time":{"start":1725237753564,"stop":1725237810323,"duration":56759}},{"uid":"489e42f84c847761","reportUrl":"https://status-im.github.io/status-cli-tests/186//#testresult/489e42f84c847761","status":"passed","time":{"start":1725151555673,"stop":1725151603426,"duration":47753}},{"uid":"c0e1d39e080ba5f9","reportUrl":"https://status-im.github.io/status-cli-tests/185//#testresult/c0e1d39e080ba5f9","status":"failed","statusDetails":"AssertionError","time":{"start":1725065120523,"stop":1725065178312,"duration":57789}},{"uid":"14ae952418827c09","reportUrl":"https://status-im.github.io/status-cli-tests/184//#testresult/14ae952418827c09","status":"failed","statusDetails":"AssertionError","time":{"start":1724978712626,"stop":1724978753673,"duration":41047}},{"uid":"f1b6df1f9891698c","reportUrl":"https://status-im.github.io/status-cli-tests/183//#testresult/f1b6df1f9891698c","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=39078): Read timed out. (read timeout=10)","time":{"start":1724892351779,"stop":1724892406277,"duration":54498}},{"uid":"c398379ad0c65420","reportUrl":"https://status-im.github.io/status-cli-tests/182//#testresult/c398379ad0c65420","status":"passed","time":{"start":1724806124477,"stop":1724806172188,"duration":47711}},{"uid":"377ffbad6013ad16","reportUrl":"https://status-im.github.io/status-cli-tests/181//#testresult/377ffbad6013ad16","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=22353): Read timed out. (read timeout=10)","time":{"start":1724719878758,"stop":1724719947056,"duration":68298}},{"uid":"a0b53d24452b6b10","reportUrl":"https://status-im.github.io/status-cli-tests/180//#testresult/a0b53d24452b6b10","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=2940): Read timed out. (read timeout=10)","time":{"start":1724633685690,"stop":1724633740178,"duration":54488}},{"uid":"5b0934dedfb2feaa","reportUrl":"https://status-im.github.io/status-cli-tests/179//#testresult/5b0934dedfb2feaa","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=30155): Read timed out. (read timeout=10)","time":{"start":1724547059659,"stop":1724547114152,"duration":54493}},{"uid":"c841e4830198b080","reportUrl":"https://status-im.github.io/status-cli-tests/178//#testresult/c841e4830198b080","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=23527): Read timed out. (read timeout=10)","time":{"start":1724460718245,"stop":1724460772734,"duration":54489}},{"uid":"8186f4326565dd2","reportUrl":"https://status-im.github.io/status-cli-tests/177//#testresult/8186f4326565dd2","status":"passed","time":{"start":1724373933067,"stop":1724373980812,"duration":47745}},{"uid":"bc796f7ddaccfdc3","reportUrl":"https://status-im.github.io/status-cli-tests/176//#testresult/bc796f7ddaccfdc3","status":"failed","statusDetails":"AssertionError: 2 community joins out of 10: Leave Timestamp: 00:44:44, Community ID: 0x0200d3d6716ab51102ce03b7914ce93af9462b64a7362dd4d45d1d963defc1482d, Error: Comunity doesn't have the initial number of members after join and leave, so leave probably failed\nassert 1 == 8\n +  where 1 = len({'0x04f2b7818d5afff99abc74262cff2cce5dbcaa60ceb41c6b98acd828f299dd1e921e2a09f6f54198416b2e81aaaacea034bcab04a1640fcb7d50b153fce95eae10': {'roles': [1]}})\nLeave Timestamp: 00:44:44, Community ID: 0x02622c996e82e51f12fd32a12445656fe3bbc29ad82fdd821156615ceaf24081ef, Error: Comunity doesn't have the initial number of members after join and leave, so leave probably failed\nassert 1 == 8\n +  where 1 = len({'0x04b08820adfd364e00807ade88629f594cc50aff8e848ad96c9baa0de5235e8fca43c260ef1462f6adbd284a484516faef1fd80b3cf22041d94ff781b35fa66040': {'roles': [1]}})","time":{"start":1724287436675,"stop":1724287484350,"duration":47675}}]},"tags":["@pytest.mark.usefixtures('start_1_node')"]},"source":"d914f5d744184bf.json","parameterValues":[]}